name: Generate Neon Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Neon Snake
        uses: Platane/snk@v3
        with:
          github_user_name: kaviyaazhagesan23-ui
          outputs: |
            dist/github-snake.svg?palette=github-dark&color_snake=%2300FFFF&color_dots=%230B0B18%3B%237B2CFF%3B%2300FFFF%3B%23FF00FF%3B%2300FF85
            dist/github-snake-dark.svg?palette=github-dark&color_snake=%2300FFFF&color_dots=%230B0B18%3B%237B2CFF%3B%2300FFFF%3B%23FF00FF%3B%2300FF85

      - name: Publish Neon Snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
